version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_restaurante
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_restaurante
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: ${PMA_USER}          # puedes poner ${MYSQL_USER} o "root"
      PMA_PASSWORD: ${PMA_PASSWORD}  # si PMA_USER=root, usa ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_restaurante
    restart: always
    ports:
      - "${BACKEND_PORT}:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}

  frontend:
    build:
      context: ./frontend
    container_name: frontend_restaurante
    restart: always
    ports:
      - "${FRONTEND_PORT}:4200"
    volumes:
      - ./frontend:/usr/src/app
    command: npm start

  n8n:
    image: n8nio/n8n
    container_name: n8n_restaurante
    restart: always
    environment:
      GENERIC_TIMEZONE: Europe/Madrid
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD}
      DB_TYPE: sqlite
      DB_SQLITE_DATABASE: /home/node/.n8n/database.sqlite
    ports:
      - "${N8N_PORT}:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n

networks:
  default:
    driver: bridge
